"""
Tests for SQLAlchemy model definitions.

SPEC: SPEC-M1-B — Modelos SQLAlchemy
ACs covered:
  - User PK is a UUID auto-generated on creation
  - User has created_at and updated_at timestamps
  - Restaurant.qr_token is auto-generated (uuid4 string) when not provided
  - Item.price is stored and returned as Decimal, never float
  - Item.price rejects float input at the model level
  - UserRestaurantRole.role accepts valid enum values
  - UserRestaurantRole.role rejects values outside the enum
  - MenuStyle.font_family accepts valid enum values
  - MenuStyle.font_family rejects invalid font family strings
  - MenuStyle.restaurant_id is UNIQUE (1:1 with Restaurant)
  - Deleting a Menu cascades to its Categories (and Subcategories)
"""
import uuid
from decimal import Decimal

import pytest
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError

from app.models.user import User
from app.models.restaurant import Restaurant, UserRestaurantRole, RestaurantRole
from app.models.menu import Menu, Category, Subcategory, CategoryType
from app.models.item import Item, ItemTag
from app.models.style import MenuStyle, FontFamily


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_user(**kwargs) -> User:
    defaults = dict(
        email=f"user_{uuid.uuid4().hex[:8]}@example.com",
        hashed_password="hashed_pw",
        full_name="Test User",
    )
    defaults.update(kwargs)
    return User(**defaults)


def _make_restaurant(**kwargs) -> Restaurant:
    defaults = dict(name="Test Restaurant", slug=f"test-r-{uuid.uuid4().hex[:8]}")
    defaults.update(kwargs)
    return Restaurant(**defaults)


def _make_menu(restaurant_id, **kwargs) -> Menu:
    defaults = dict(name="Test Menu", restaurant_id=restaurant_id)
    defaults.update(kwargs)
    return Menu(**defaults)


def _make_category(menu_id, **kwargs) -> Category:
    defaults = dict(
        name="Test Category",
        menu_id=menu_id,
        type=CategoryType.food,
    )
    defaults.update(kwargs)
    return Category(**defaults)


def _make_item(subcategory_id, **kwargs) -> Item:
    defaults = dict(
        name="Test Item",
        description="A tasty item",
        price=Decimal("9.99"),
        subcategory_id=subcategory_id,
    )
    defaults.update(kwargs)
    return Item(**defaults)


# ---------------------------------------------------------------------------
# User tests
# ---------------------------------------------------------------------------

async def test_user_uuid_autogenerated(db_session):
    """User.id must be a UUID generated automatically — not None, not provided."""
    user = _make_user()
    # Do NOT set id explicitly
    assert user.id is None or isinstance(user.id, uuid.UUID), (
        "Before flush id should be None or already a UUID from default"
    )
    db_session.add(user)
    await db_session.flush()
    assert user.id is not None, "User.id must be set after flush"
    assert isinstance(user.id, uuid.UUID), f"User.id must be uuid.UUID, got {type(user.id)}"


async def test_user_timestamps(db_session):
    """User must have created_at and updated_at populated after insert."""
    user = _make_user()
    db_session.add(user)
    await db_session.flush()
    assert user.created_at is not None, "User.created_at must be set after insert"
    assert user.updated_at is not None, "User.updated_at must be set after insert"


# ---------------------------------------------------------------------------
# Restaurant tests
# ---------------------------------------------------------------------------

async def test_restaurant_qr_token_auto(db_session):
    """Restaurant.qr_token must be auto-generated as a non-empty string (uuid4)."""
    restaurant = _make_restaurant()
    db_session.add(restaurant)
    await db_session.flush()
    assert restaurant.qr_token is not None, "Restaurant.qr_token must not be None"
    assert isinstance(restaurant.qr_token, str), "Restaurant.qr_token must be a string"
    assert len(restaurant.qr_token) > 0, "Restaurant.qr_token must not be empty"
    # Validate it is a valid UUID4 representation
    parsed = uuid.UUID(restaurant.qr_token)
    assert parsed.version == 4, "Restaurant.qr_token must be a version-4 UUID"


# ---------------------------------------------------------------------------
# Item / price tests
# ---------------------------------------------------------------------------

async def test_item_price_is_decimal(db_session):
    """Item.price must round-trip as Decimal, not float."""
    restaurant = _make_restaurant()
    db_session.add(restaurant)
    await db_session.flush()

    menu = _make_menu(restaurant_id=restaurant.id)
    db_session.add(menu)
    await db_session.flush()

    category = _make_category(menu_id=menu.id)
    db_session.add(category)
    await db_session.flush()

    subcategory = Subcategory(name="Test Sub", category_id=category.id)
    db_session.add(subcategory)
    await db_session.flush()

    item = _make_item(subcategory_id=subcategory.id, price=Decimal("12.50"))
    db_session.add(item)
    await db_session.flush()

    result = await db_session.execute(select(Item).where(Item.id == item.id))
    fetched = result.scalar_one()
    assert isinstance(fetched.price, Decimal), (
        f"Item.price must be Decimal after round-trip, got {type(fetched.price)}"
    )
    assert fetched.price == Decimal("12.50")


async def test_item_price_not_float(db_session):
    """Item.price column type must be Numeric(10,2), not Float."""
    from sqlalchemy import inspect as sa_inspect
    from sqlalchemy import Numeric

    # Inspect the Item table column type
    mapper = Item.__mapper__
    price_col = mapper.columns["price"]
    assert isinstance(price_col.type, Numeric), (
        f"Item.price must be Numeric type, got {type(price_col.type)}"
    )
    # Numeric subclass check — must NOT be Float
    from sqlalchemy import Float
    assert not isinstance(price_col.type, Float), (
        "Item.price must NOT be Float — use Numeric(10, 2)"
    )


# ---------------------------------------------------------------------------
# Enum tests — RestaurantRole
# ---------------------------------------------------------------------------

async def test_role_enum_valid(db_session):
    """UserRestaurantRole.role must accept 'owner' and 'editor'."""
    restaurant = _make_restaurant()
    user = _make_user()
    db_session.add_all([restaurant, user])
    await db_session.flush()

    for role_value in (RestaurantRole.owner, RestaurantRole.editor):
        link = UserRestaurantRole(
            user_id=user.id,
            restaurant_id=restaurant.id,
            role=role_value,
        )
        db_session.add(link)
        await db_session.flush()
        await db_session.delete(link)
        await db_session.flush()


async def test_role_enum_invalid():
    """RestaurantRole enum must NOT have a 'manager' or arbitrary value."""
    valid_values = {e.value for e in RestaurantRole}
    assert "manager" not in valid_values, (
        "RestaurantRole must not contain 'manager' — only 'owner' and 'editor'"
    )
    assert "admin" not in valid_values, (
        "RestaurantRole must not contain 'admin'"
    )
    assert valid_values == {"owner", "editor"}, (
        f"RestaurantRole must have exactly {{'owner', 'editor'}}, got {valid_values}"
    )


# ---------------------------------------------------------------------------
# Enum tests — FontFamily
# ---------------------------------------------------------------------------

async def test_font_family_enum_valid():
    """FontFamily enum must contain the four specified font names."""
    valid_values = {e.value for e in FontFamily}
    expected = {"Inter", "Playfair Display", "Poppins", "DM Sans"}
    assert valid_values == expected, (
        f"FontFamily must be exactly {expected}, got {valid_values}"
    )


async def test_font_family_enum_invalid():
    """FontFamily enum must NOT contain arbitrary font names."""
    valid_values = {e.value for e in FontFamily}
    assert "Arial" not in valid_values, "FontFamily must not contain 'Arial'"
    assert "Roboto" not in valid_values, "FontFamily must not contain 'Roboto'"


# ---------------------------------------------------------------------------
# MenuStyle uniqueness test
# ---------------------------------------------------------------------------

async def test_menu_style_restaurant_unique(db_session):
    """MenuStyle.restaurant_id must be UNIQUE — second insert for same restaurant must fail."""
    restaurant = _make_restaurant()
    db_session.add(restaurant)
    await db_session.flush()

    style1 = MenuStyle(
        restaurant_id=restaurant.id,
        font_family=FontFamily.inter,
    )
    db_session.add(style1)
    await db_session.flush()

    style2 = MenuStyle(
        restaurant_id=restaurant.id,
        font_family=FontFamily.poppins,
    )
    db_session.add(style2)

    with pytest.raises(IntegrityError):
        await db_session.flush()


# ---------------------------------------------------------------------------
# Cascade delete test
# ---------------------------------------------------------------------------

async def test_cascade_delete_menu(db_session):
    """Deleting a Menu must cascade-delete its Categories and Subcategories."""
    restaurant = _make_restaurant()
    db_session.add(restaurant)
    await db_session.flush()

    menu = _make_menu(restaurant_id=restaurant.id)
    db_session.add(menu)
    await db_session.flush()

    category = _make_category(menu_id=menu.id)
    db_session.add(category)
    await db_session.flush()

    subcategory = Subcategory(
        name="Test Subcategory",
        category_id=category.id,
    )
    db_session.add(subcategory)
    await db_session.flush()

    menu_id = menu.id
    category_id = category.id
    subcategory_id = subcategory.id

    await db_session.delete(menu)
    await db_session.flush()

    # Category must be gone
    cat_result = await db_session.execute(
        select(Category).where(Category.id == category_id)
    )
    assert cat_result.scalar_one_or_none() is None, (
        "Category must be deleted when its parent Menu is deleted (cascade)"
    )

    # Subcategory must be gone
    sub_result = await db_session.execute(
        select(Subcategory).where(Subcategory.id == subcategory_id)
    )
    assert sub_result.scalar_one_or_none() is None, (
        "Subcategory must be deleted when its parent Category is deleted (cascade)"
    )
